version: '3.8'

services:

  web:
    container_name: kitchen-helper-dev
    build: ./
#    command: python3 api.py
    command: uvicorn api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - postgres__host=db
      - postgres__port=5432
      - postgres__user=<USER>
      - postgres__password=<PASSWORD>
      - postgres__database='kitchen-helper'
    depends_on:
      - db

  db:
    container_name: kitchen-helper-db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - kitchen-helper-db-volume:/var/lib/postgreslq/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=<USER>
      - POSTGRES_PASSWORD=<PASSWORD>

volumes:
  kitchen-helper-db-volume:
    driver: local
