#To work properly you have to create .env file with credentials
version: '3.8'

services:

  web:
    container_name: kitchen-helper-dev
    build: ./
    command: python3 api.py
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - postgres__host=db
      - postgres__port=5432
      - postgres__user=${POSTGRES_USER}
      - postgres__password=${POSTGRES_PASSWORD}
      - postgres__database=kitchen-helper
    depends_on:
      - db

  db:
    container_name: kitchen-helper-db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - kitchen-helper-db-volume:/var/lib/postgreslq/data
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  kitchen-helper-db-volume:
    driver: local
