#To work properly you have to create .env file with credentials
version: '3.8'

services:

  web:
    container_name: kitchen-helper-web
    build: ./
    command: python3 api.py
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - database=postgres
      - postgres__host=db
      - postgres__port=5432
      - postgres__user=${POSTGRES_USER}
      - postgres__password=${POSTGRES_PASSWORD}
      - postgres__database=kitchen-helper
      - rabbitmq__user=${RABBITMQ_USER}
      - rabbitmq__password=${RABBITMQ_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER}${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:${CELERY_PORT}//
      - CELERY_RESULT_BACKEND=${CELERY_BACKEND}
    depends_on:
      - db
      - rabbitmq
      - jaeger

  db:
    container_name: kitchen-helper-db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - kitchen-helper-db-volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  rabbitmq:
    container_name: kitchen-helper-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - kitchen-helper-rabbitmq-volume:/var/lib/rabbitmq

  celery-workers:
    container_name: kitchen-helper-celery-workers
    build: ./
    command: celery -A configuration.celery worker --loglevel=info --logfile=./logs/celery-worker.log
    volumes:
      - ./:/usr/src/app
    environment:
      - postgres__host=db
      - postgres__port=5432
      - postgres__user=${POSTGRES_USER}
      - postgres__password=${POSTGRES_PASSWORD}
      - postgres__database=kitchen-helper
      - rabbitmq__user=${RABBITMQ_USER}
      - rabbitmq__password=${RABBITMQ_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER}${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:${CELERY_PORT}//
      - CELERY_RESULT_BACKEND=${CELERY_BACKEND}
    depends_on:
      - db
      - rabbitmq

  celery-beat:
    container_name: kitchen-helper-celery-beat
    build: ./
    command: celery -A configuration.celery beat --loglevel=info --logfile=./logs/celery-beat.log
    volumes:
      - ./:/usr/src/app
    environment:
      - database=sqlite
      - CELERY_BROKER_URL=${CELERY_BROKER}${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:${CELERY_PORT}//
      - CELERY_RESULT_BACKEND=${CELERY_BACKEND}
    depends_on:
      - db
      - rabbitmq

  jaeger:
    container_name: kitchen-helper-jaeger
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
      - "6831:6831"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - kitchen-helper-jaeger-volume:/var/lib/jaeger

volumes:
  kitchen-helper-db-volume:
    driver: local
  kitchen-helper-rabbitmq-volume:
    driver: local
  kitchen-helper-jaeger-volume:
    driver: local
