"""add recipe ingredient relation

Revision ID: 0aa4778d47d1
Revises: 6f16aa3da54c
Create Date: 2024-01-05 16:42:43.644415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa4778d47d1'
down_revision: Union[str, None] = '37d1ebc63a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'RECIPE_INGREDIENTS_MAPPING',
        sa.Column('recipe_id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ['ingredient_id'],
            ['INGREDIENTS.id'],
        ),
        sa.ForeignKeyConstraint(
            ['recipe_id'],
            ['RECIPES.id'],
        ),
        sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RECIPE_INGREDIENTS_MAPPING')
    # ### end Alembic commands ###
