"""Remove user columns

Revision ID: 2148d4587f3e
Revises: 663d0c834556
Create Date: 2023-11-16 19:39:55.889286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2148d4587f3e'
down_revision: Union[str, None] = '663d0c834556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RECIPES', 'created_by')
    op.drop_column('RECIPES', 'updated_by')
    op.drop_column('RECIPE_CATEGORIES', 'created_by')
    op.drop_column('RECIPE_CATEGORIES', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RECIPE_CATEGORIES', sa.Column('updated_by', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('RECIPE_CATEGORIES', sa.Column('created_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('RECIPES', sa.Column('updated_by', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('RECIPES', sa.Column('created_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
