"""add user updated fields

Revision ID: 221bb1f84e86
Revises: 4d0be8f2651d
Create Date: 2023-12-14 09:50:10.480495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "221bb1f84e86"
down_revision: Union[str, None] = "4d0be8f2651d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Users", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.add_column(
        "Users",
        sa.Column(
            "updated_on",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.create_foreign_key(None, "Users", "Users", ["updated_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Users", type_="foreignkey")
    op.drop_column("Users", "updated_on")
    op.drop_column("Users", "updated_by")
    # ### end Alembic commands ###
