"""allow picture to be empty

Revision ID: 37d1ebc63a4e
Revises: daa61bc3ead7
Create Date: 2024-01-10 19:56:45.438431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d1ebc63a4e'
down_revision: Union[str, None] = 'daa61bc3ead7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RECIPES', 'picture', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RECIPES', 'picture', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
