"""“add_recipe_complexity”

Revision ID: 39b0a24527e0
Revises: f6fac2627b53
Create Date: 2023-11-11 11:13:58.463684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b0a24527e0'
down_revision: Union[str, None] = 'f6fac2627b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RECIPES', sa.Column('complexity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RECIPES', 'complexity')
    # ### end Alembic commands ###
