"""Remove complexity and time to prepare columns

Revision ID: 3eac26f37e69
Revises: 6f16aa3da54c
Create Date: 2024-01-08 21:34:47.415687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eac26f37e69'
down_revision: Union[str, None] = '6f16aa3da54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RECIPES', 'complexity')
    op.drop_column('RECIPES', 'time_to_prepare')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RECIPES', sa.Column('time_to_prepare', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(
        'RECIPES', sa.Column('complexity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
