"""add_ingredients_models

Revision ID: 49b601170250
Revises: e97968546870
Create Date: 2023-12-14 20:44:14.537082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49b601170250'
down_revision: Union[str, None] = 'e97968546870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('INGREDIENTS', 'measurement',
               existing_type=postgresql.ENUM('KG', 'ML', 'G', 'L', 'OZ', 'LB', 'CUP', name='measurementunits'),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('INGREDIENTS', 'measurement',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('KG', 'ML', 'G', 'L', 'OZ', 'LB', 'CUP', name='measurementunits'),
               existing_nullable=False)
    # ### end Alembic commands ###
