"""add-created-by-int-columns

Revision ID: 4d0be8f2651d
Revises: 78a3e103b080
Create Date: 2023-12-11 20:06:12.410906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d0be8f2651d"
down_revision: Union[str, None] = "78a3e103b080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Roles", sa.Column("created_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "Roles", "Users", ["created_by"], ["id"])
    op.add_column("user_roles", sa.Column("added_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user_roles", "Users", ["added_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.drop_column("user_roles", "added_by")
    op.drop_constraint(None, "Roles", type_="foreignkey")
    op.drop_column("Roles", "created_by")
    # ### end Alembic commands ###
