"""removed nutrients fields from recipe

Revision ID: 53eaad816d48
Revises: 0aa4778d47d1
Create Date: 2024-01-11 12:53:05.900858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53eaad816d48'
down_revision: Union[str, None] = '37d1ebc63a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RECIPES', 'fats')
    op.drop_column('RECIPES', 'cholesterol')
    op.drop_column('RECIPES', 'calories')
    op.drop_column('RECIPES', 'carbo')
    op.drop_column('RECIPES', 'proteins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'RECIPES', sa.Column('proteins', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column('RECIPES', sa.Column('carbo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column(
        'RECIPES', sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        'RECIPES', sa.Column('cholesterol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column('RECIPES', sa.Column('fats', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
