"""add ingredient model

Revision ID: 931f4b8673d8
Revises: 221bb1f84e86
Create Date: 2024-01-04 12:16:29.536137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931f4b8673d8'
down_revision: Union[str, None] = '221bb1f84e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'INGREDIENTS',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column('carbo', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column('fats', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column('cholesterol', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            'measurement',
            sa.Enum(
                'KG',
                'GRAM',
                'LITER',
                'MILLILITER',
                'TEASPOON',
                'TABLESPOON',
                'CUP',
                'PINCH',
                'PIECE',
                'OUNCE',
                'POUND',
                'FLUID_OUNCE',
                'GALLON',
                'QUART',
                'PINT',
                name='ingredientmeasurementenum',
            ),
            nullable=False,
        ),
        sa.Column(
            'category',
            sa.Enum(
                'PANTRY_ESSENTIALS',
                'VEGETABLES_AND_GREENS',
                'FRUITS',
                'MEAT_AND_POULTRY',
                'SEAFOOD',
                'DAIRY',
                'SPICES_AND_SEASONINGS',
                'GRAINS_AND_PASTA',
                'CONDIMENTS',
                'BAKING_INGREDIENTS',
                'BEVERAGES',
                'NUTS_AND_SEEDS',
                'SWEETENERS',
                'SNACKS',
                'MISCELLANEOUS',
                name='ingredientcategoryenum',
            ),
            nullable=False,
        ),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('updated_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_on', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['Users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['deleted_by'],
            ['Users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['updated_by'],
            ['Users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_INGREDIENTS_name'), 'INGREDIENTS', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_INGREDIENTS_name'), table_name='INGREDIENTS')
    op.drop_table('INGREDIENTS')
    # ### end Alembic commands ###
