"""add token model and is_email_confirmed field to user

Revision ID: 97b56ec45dfa
Revises: 39b0a24527e0
Create Date: 2023-11-30 11:46:57.474033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b56ec45dfa'
down_revision: Union[str, None] = '39b0a24527e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CONFIRMATION_TOKEN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expired_on', sa.DateTime(), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Users', sa.Column('is_email_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_email_confirmed')
    op.drop_table('CONFIRMATION_TOKEN')
    # ### end Alembic commands ###
