"""Add user columns

Revision ID: abc4a9801f4e
Revises: 2148d4587f3e
Create Date: 2023-11-16 19:41:21.392643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abc4a9801f4e"
down_revision: Union[str, None] = "2148d4587f3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("RECIPES", sa.Column("created_by", sa.Integer(), nullable=False))
    op.add_column("RECIPES", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.add_column(
        "RECIPE_CATEGORIES", sa.Column("created_by", sa.Integer(), nullable=False)
    )
    op.add_column(
        "RECIPE_CATEGORIES", sa.Column("updated_by", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("RECIPE_CATEGORIES", "updated_by")
    op.drop_column("RECIPE_CATEGORIES", "created_by")
    op.drop_column("RECIPES", "updated_by")
    op.drop_column("RECIPES", "created_by")
    # ### end Alembic commands ###
