"""add_ingredients_models

Revision ID: c6875473ed21
Revises: 221bb1f84e86
Create Date: 2023-12-28 10:27:28.176094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6875473ed21'
down_revision: Union[str, None] = '221bb1f84e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'INGREDIENT_CATEGORIES',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('updated_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['Users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['updated_by'],
            ['Users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'INGREDIENTS',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('calories', sa.Float(), nullable=False),
        sa.Column('carbo', sa.Float(), nullable=False),
        sa.Column('fats', sa.Float(), nullable=False),
        sa.Column('protein', sa.Float(), nullable=False),
        sa.Column('cholesterol', sa.Float(), nullable=False),
        sa.Column('measurement', sa.String(length=100), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_on', sa.DateTime(), nullable=True),
        sa.Column('deleted_by', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['INGREDIENT_CATEGORIES.id'],
        ),
        sa.ForeignKeyConstraint(
            ['deleted_by'],
            ['Users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_INGREDIENTS_name'), 'INGREDIENTS', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_INGREDIENTS_name'), table_name='INGREDIENTS')
    op.drop_table('INGREDIENTS')
    op.drop_table('INGREDIENT_CATEGORIES')
    # ### end Alembic commands ###
