"""Added published and deleted fileds to Recipe

Revision ID: e3fddc53bd36
Revises: 663d0c834556
Create Date: 2023-11-15 13:15:20.511250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fddc53bd36'
down_revision: Union[str, None] = '663d0c834556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RECIPES', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('RECIPES', sa.Column('published_on', sa.DateTime(), nullable=True))
    op.add_column('RECIPES', sa.Column('published_by', sa.String(length=30), nullable=True))
    op.add_column('RECIPES', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('RECIPES', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    op.add_column('RECIPES', sa.Column('deleted_by', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RECIPES', 'deleted_by')
    op.drop_column('RECIPES', 'deleted_on')
    op.drop_column('RECIPES', 'is_deleted')
    op.drop_column('RECIPES', 'published_by')
    op.drop_column('RECIPES', 'published_on')
    op.drop_column('RECIPES', 'is_published')
    # ### end Alembic commands ###
