"""changed fields from int to fk in Recipe

Revision ID: ef1413eb13d9
Revises: abc4a9801f4e
Create Date: 2023-11-16 21:04:10.432509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1413eb13d9'
down_revision: Union[str, None] = 'abc4a9801f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RECIPES', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('RECIPES', sa.Column('published_on', sa.DateTime(), nullable=True))
    op.add_column('RECIPES', sa.Column('published_by', sa.Integer(), nullable=True))
    op.add_column('RECIPES', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('RECIPES', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    op.add_column('RECIPES', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'RECIPES', 'Users', ['published_by'], ['id'])
    op.create_foreign_key(None, 'RECIPES', 'Users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'RECIPES', 'Users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'RECIPES', 'Users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'RECIPE_CATEGORIES', 'Users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'RECIPE_CATEGORIES', 'Users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'RECIPE_CATEGORIES', type_='foreignkey')
    op.drop_constraint(None, 'RECIPE_CATEGORIES', type_='foreignkey')
    op.drop_constraint(None, 'RECIPES', type_='foreignkey')
    op.drop_constraint(None, 'RECIPES', type_='foreignkey')
    op.drop_constraint(None, 'RECIPES', type_='foreignkey')
    op.drop_constraint(None, 'RECIPES', type_='foreignkey')
    op.drop_column('RECIPES', 'deleted_by')
    op.drop_column('RECIPES', 'deleted_on')
    op.drop_column('RECIPES', 'is_deleted')
    op.drop_column('RECIPES', 'published_by')
    op.drop_column('RECIPES', 'published_on')
    op.drop_column('RECIPES', 'is_published')
    # ### end Alembic commands ###
