"""'add_recipe_instructions'

Revision ID: f6fac2627b53
Revises: 0d117739f322
Create Date: 2023-11-09 22:42:00.202553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fac2627b53'
down_revision: Union[str, None] = '0d117739f322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RECIPE_INSTRUCTIONS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instruction', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Float(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['RECIPES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RECIPE_INSTRUCTIONS')
    # ### end Alembic commands ###
