# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication.images_pb2 as images__pb2


class ImagesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_image_url = channel.unary_unary(
            '/images.Images/get_image_url',
            request_serializer=images__pb2.ImageRequest.SerializeToString,
            response_deserializer=images__pb2.ImageResponse.FromString,
        )


class ImagesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_image_url(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'get_image_url': grpc.unary_unary_rpc_method_handler(
            servicer.get_image_url,
            request_deserializer=images__pb2.ImageRequest.FromString,
            response_serializer=images__pb2.ImageResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('images.Images', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Images(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_image_url(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/images.Images/get_image_url',
            images__pb2.ImageRequest.SerializeToString,
            images__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
