# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0busers.proto\x12\x05users\"\"\n\x0fUsernameRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"$\n\x10UsernameResponse\x12\x10\n\x08username\x18\x01 \x01(\t2H\n\x05Users\x12?\n\x0cget_username\x12\x16.users.UsernameRequest\x1a\x17.users.UsernameResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_USERNAMEREQUEST']._serialized_start = 22
    _globals['_USERNAMEREQUEST']._serialized_end = 56
    _globals['_USERNAMERESPONSE']._serialized_start = 58
    _globals['_USERNAMERESPONSE']._serialized_end = 94
    _globals['_USERS']._serialized_start = 96
    _globals['_USERS']._serialized_end = 168
# @@protoc_insertion_point(module_scope)
